[package]
name = "finne_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = {version = "1", features = ["serde"]}
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
